project_id = "fiwmlzrhwvrsrxmcstzk"

[functions.scan-item]
verify_jwt = false

[functions.generate-claim-rules]
verify_jwt = false

[functions.close-claim-sale]
verify_jwt = false

[functions.create-connect-account-link]
verify_jwt = true

[functions.get-connect-account-status]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.release-payout]
verify_jwt = true

[functions.confirm-delivery]
verify_jwt = true
